version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: src/API/Dockerfile
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "uwhADwJAZdWoRnNTf4r6"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"  
  
