version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: ./src/API
      dockerfile: Dockerfile
    environment:
      ConnectionStrings__DefaultConnection: "Server=mssql;Database=master;User Id=Centrica;Password=${Centrica_PASSWORD}"
    depends_on:
      - mssql
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "${sa_PASSWORD}"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - ./db:/db
    command:
      - /bin/bash
      - -c
      - |
        /opt/mssql/bin/sqlservr & sleep 20 ; /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P '${sa_PASSWORD}' -d master -i /db/initialize-db.sql -v User_PASSWORD="${Centrica_PASSWORD}" ; sleep infinity

